
-- ============================
-- A) ACTIVITY RESET (safe for dev)
-- ============================
-- Child tables first
TRUNCATE TABLE doctor_call_products RESTART IDENTITY CASCADE;
TRUNCATE TABLE doctor_calls RESTART IDENTITY CASCADE;
TRUNCATE TABLE missed_doctors RESTART IDENTITY CASCADE;
TRUNCATE TABLE dcr_submissions RESTART IDENTITY CASCADE;

TRUNCATE TABLE chemist_stock_flags RESTART IDENTITY CASCADE;
TRUNCATE TABLE chemist_visits RESTART IDENTITY CASCADE;
TRUNCATE TABLE chemist_report_submissions RESTART IDENTITY CASCADE;

TRUNCATE TABLE mileage_entries RESTART IDENTITY CASCADE;

-- ============================
-- B) OPTIONAL: remove old demo-only master rows
-- ============================
-- Keep core users/routes/territories/products unless you are rebuilding from scratch.
-- Delete only rows that are clearly demo-generated by name/code patterns.

-- Doctor route mappings first, then doctors
DELETE FROM doctor_routes
WHERE doctor_id IN (
  SELECT id FROM doctors
  WHERE name LIKE 'Dr Demo %'
);

DELETE FROM doctors
WHERE name LIKE 'Dr Demo %';

-- Remove extra demo chemists (only known demo names)
DELETE FROM chemists
WHERE name LIKE 'Demo Pharmacy %';

-- Optional demo products (keep base seed PRD_SEED_01..03)
DELETE FROM products
WHERE code LIKE 'PRD_DEMO_%';

