server:
  port: ${PORT:9090}
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        http-only: true
        secure: ${REPNEXA_SESSION_COOKIE_SECURE:true}
        same-site: LAX

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/repnexa}
    username: ${SPRING_DATASOURCE_USERNAME:repnexa}
    password: ${SPRING_DATASOURCE_PASSWORD:repnexa}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
